<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkpBH0H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkpBH0H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXkpBH0H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXkpBH0H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXkpBH0H\App_KernelDevDebugContainer([
    'container.build_hash' => 'XkpBH0H',
    'container.build_id' => '9af344ce',
    'container.build_time' => 1680272324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkpBH0H');
